config/routes.rb
Rails.application.routes.draw do

  get 'list_stock/index'

  get 'list_stock/new'

  get 'list_stock/create'

  get 'list_stock/edite'

  get 'list_stock/delete'

  resources :stocks

  root 'home#index'
  
  devise_for :users
  
  get 'home/index'

  resources :my_stocks
  resources :rate_charts

  get 'rate_charts_current' => 'rate_charts#current'

  get 'update_stock_list' => 'stocks#update_stock_list'

  get 'current_assets' => 'my_stocks#current_assets'

  resources :list_stocks
  

end

app/models/my_stock.rb
# == Schema Information
#
# Table name: my_stocks
#
#  id                        :integer          not null, primary key
#  symbol                    :string
#  purchase_date             :date
#  purchase_price            :decimal(12, 2)   default(0.0)
#  purchase_commission       :decimal(12, 2)   default(0.0)
#  purchase_market_right     :decimal(12, 2)   default(0.0)
#  sale_date                 :date
#  sale_price                :decimal(12, 2)   default(0.0)
#  sale_market_right         :decimal(12, 2)   default(0.0)
#  user_id                   :integer
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  sale_commission           :decimal(12, 2)   default(0.0)
#  quantity                  :integer          default(0)
#  purchase_market_right_iva :decimal(12, 2)   default(0.0)
#  sale_market_right_iva     :decimal(12, 2)   default(0.0)
#  purchase_commission_iva   :decimal(12, 2)   default(0.0)
#  sale_commission_iva       :decimal(12, 2)   default(0.0)
#  type_stock                :integer
#

class MyStock < ActiveRecord::Base
  after_initialize :default_values
  
  belongs_to :user

  validates :user, presence: true
  validates :symbol, presence: true
  validates :type_stock, presence: true
  validates :quantity, presence: true, numericality: { greater_than: 0 }
  validates :purchase_price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :purchase_commission, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :purchase_commission_iva, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :purchase_market_right, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :purchase_market_right_iva, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :sale_price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :sale_commission, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :sale_commission_iva, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :sale_market_right, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :sale_market_right_iva, presence: true, numericality: { greater_than_or_equal_to: 0 }
  
  def subtotal_purchase
    self.quantity * self.purchase_price
  end
  
  def tax_purchase
    self.purchase_commission + self.purchase_commission_iva + self.purchase_market_right + self.purchase_market_right_iva
  end
  
  def total_purchase
    self.subtotal_purchase + self.tax_purchase
  end

  def subtotal_sale
    self.quantity * showed_sale_price
  end
  
  def tax_sale
    self.sale_commission + self.sale_commission_iva + self.sale_market_right + self.sale_market_right_iva
  end
  
  def total_sale
    total_sale = subtotal_sale - self.tax_sale
  end
  
  def result
    self.total_sale - self.total_purchase
  end
  
  def days
    final_date = (self.sale_date) ? self.sale_date : Date.today
    days = final_date - self.purchase_date
    days.to_i
  end
  
  def variation
    variation = (self.total_sale * 100 / self.total_purchase) - 100
    variation.round(2)
  end
  
  def variation_anual
    var_anual = 365 * self.variation / self.days
    var_anual.round(2)
  end

  def showed_sale_price
    if self.sale_price > 0
      self.sale_price
    else
      self.current_price
    end
  end

  def current_price
    if symbol
      yahoo_client = YahooFinance::Client.new
      data = yahoo_client.quote(symbol + ".BA")
      current_stock_price = data.last_trade_price.to_f
      setCurrentSaleValues(self.quantity, current_stock_price)
      current_stock_price
    else
      0
    end
  end

  def sold
    (self.sale_date.nil?) ? 1 : 2
  end
  
  protected
    
  def default_values
    self.purchase_price ||= 0.00
    self.purchase_commission ||= 0.00
    self.purchase_commission_iva ||= 0.00
    self.purchase_market_right ||= 0.00
    self.purchase_market_right_iva ||= 0.00
    self.sale_price ||= 0.00
    self.sale_commission ||= 0.00
    self.sale_commission_iva ||= 0.00
    self.sale_market_right ||= 0.00
    self.sale_market_right_iva ||= 0.00
  end

  def setCurrentSaleValues(quantity, current_stock_price)
    rc = RateChart.new
    current_user = self.user
    sale_chart = rc.current(current_user, Date.today, self.type_stock, "Sale")
    amount = (current_stock_price * quantity)
    if sale_chart
      self.sale_commission = sale_chart.commission * amount / 100
      if self.sale_commission < sale_chart.commission_min
        self.sale_commission = sale_chart.commission_min
      end
      self.sale_commission_iva = sale_chart.commission_iva * self.sale_commission / 100
      self.sale_market_right = sale_chart.market_right * amount / 100
      self.sale_market_right_iva = sale_chart.market_right_iva * self.sale_market_right / 100
    end
  end

end

app/controllers/my_stocks_controller.rb
class MyStocksController < ApplicationController
  before_action :owner, only: [:show, :edit, :update]

  def show

  end
  
  def index
    @my_stocks = current_user.my_stocks
    @my_stocks = @my_stocks.sort_by { |a, b| a.symbol > b.symbol }
  end
  
  def update
    if @stock.update(stock_params)
      redirect_to root_path
    else
      flash[:error] = "Error al actualizar"
      render :edit
    end
  end
  
  def new
    @stock = MyStock.new()
  end
  
  def create
    @stock = MyStock.new(stock_params)
    @stock.user = current_user
    
    if @stock.save
      redirect_to root_path
    else
      flash[:error] = "Error al guardar"
      render :new
    end
  end

  def current_assets
    my_stocks = current_user.my_stocks

    total = 0
    my_stocks.each do |stock|
      if stock.sale_date == nil
        total = stock.total_sale
      end
    end

    if total = 0
      total = 1
    end

    symbols = []
    prices = []
    my_stocks.each do |stock|
      if stock.sale_date == nil
        symbols << [stock.symbol, stock.total_sale / total]
      end
    end

    if symbols.size == 0
      symbols << ["Ninguno", 1]
    end

    result = symbols.map do |sym, price|
      { label: sym, data: price }
    end

    result = result.to_json

    respond_to do |format|
      format.json { render json: result}
    end
  end
  
  protected
  
  def owner
    @stock = MyStock.find(params[:id])
    if @stock.user != current_user
      flash[:error] = "No podes hacer eso!"
      redirect_to root_path
    end
  end
  
  def stock_params
    params.require(:my_stock).permit(:symbol, :quantity, :purchase_date, :purchase_price, :purchase_commission,
      :purchase_market_right, :purchase_commission_iva, :purchase_market_right_iva, :sale_date, :sale_price, 
      :sale_commission, :sale_market_right, :sale_commission_iva, :sale_market_right_iva, :user_id, :type_stock )
  end
  
end

app/helpers/my_stock_helper.rb
module MyStockHelper
end

app/views/my_stocks/_current_purchase_rate_chart.html.erb
<div class="col-lg-4">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Cuadro Tarifario Vigente</h3>
		</div>
		<div class="panel-body">
			<table class="table">
				<tr>
					<td>
						<p>Comisión</p>
					</td>
					<td align="right">
						<p><%= label_tag 'commission', '', id: 'purchase_current_rate_chart_commission' %> %</p>
					</td>
				</tr>
				<tr>
					<td>
						<p>Mínimo</p>
					</td>
					<td align="right">
						<p>$ <%= label_tag 'minimium commission', '', id: 'purchase_current_rate_chart_commission_min' %></p>
					</td>
				</tr>
				<tr>
					<td>
						<p>IVA comisión</p>
					</td>
					<td align="right">
						<p><%= label_tag 'iva commission', '', id: 'purchase_current_rate_chart_commission_iva' %> %</p>
					</td>
				</tr>
				<tr>
					<td>
						<p>Dº Mercado</p>
					</td>
					<td align="right">
						<p><%= label_tag 'iva commission', '', id: 'purchase_current_rate_chart_market_right' %> %</p>
					</td>
				</tr>
				<tr>
					<td>
						<p>IVA Dº Mercado</p>
					</td>
					<td align="right">
						<p><%= label_tag 'iva commission', '', id: 'purchase_current_rate_chart_market_right_iva' %> %</p>
					</td>
				</tr>
				<tr>
					<td colspan="2" align="center">
						<%= link_to 'Calcular', "#", remote: true, class: 'btn btn-default', id: 'calculate_purchase' %>
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>

app/views/my_stocks/_current_sale_rate_chart.html.erb
<div class="col-lg-4">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Cuadro Tarifario Vigente</h3>
		</div>
		<div class="panel-body">
			<table class="table">
				<tr>
					<td>
						<p>Comisión</p>
					</td>
					<td align="right">
						<p><%= label_tag 'commission', '', id: 'sale_current_rate_chart_commission' %> %</p>
					</td>
				</tr>
				<tr>
					<td>
						<p>Mínimo</p>
					</td>
					<td align="right">
						<p>$ <%= label_tag 'minimium commission', '', id: 'sale_current_rate_chart_commission_min' %></p>
					</td>
				</tr>
				<tr>
					<td>
						<p>IVA comisión</p>
					</td>
					<td align="right">
						<p><%= label_tag 'iva commission', '', id: 'sale_current_rate_chart_commission_iva' %> %</p>
					</td>
				</tr>
				<tr>
					<td>
						<p>Dº Mercado</p>
					</td>
					<td align="right">
						<p><%= label_tag 'iva commission', '', id: 'sale_current_rate_chart_market_right' %> %</p>
					</td>
				</tr>
				<tr>
					<td>
						<p>IVA Dº Mercado</p>
					</td>
					<td align="right">
						<p><%= label_tag 'iva commission', '', id: 'sale_current_rate_chart_market_right_iva' %> %</p>
					</td>
				</tr>
				<tr>
					<td colspan="2" align="center">
						<%= link_to 'Calcular', '#', remote: true, class: 'btn btn-default', id: 'calculate_sale' %>
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>

app/views/my_stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
	<% if @stock.errors.any? %>
		<div id="error_explanation">
			<h4><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h4>
			
			<% @stock.errors.full_messages.each do |message| %>
				<div class="alert alert-danger" role="alert">
					<p><%= message %></p>
				</div>
			<% end %>
		</div>
	<% end %>
		
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Activo</h3>
		</div>
		<div class="panel-body">
			<table class="table">
				<tr>
					<td>
						<div class="input-group">
							<%= f.label 'Símbolo' %>
							<%= f.text_field :symbol, class: "form-control", placeholder: "Símbolo" %>
						</div>
					</td>
					<td>
						<div class="input-group">
							<%= f.label 'Tipo' %>
							<%= f.select(:type_stock, options_for_select([["Acción", 1],["Bono", 2]], @stock.type_stock), {}, {class: "form-control"}) %>
						</div>
					</td>
				</tr>
				<tr>
					<td colspan="2">
						<div class="input-group">
							<%= f.label 'Cantidad' %>
							<%= f.text_field :quantity, class: "form-control", placeholder: "Cantidad" %>
						</div>
					</td>
				</tr>
			</table>
		</div>
	</div>
		
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Compra</h3>
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-lg-8">
					<table class="table">
						<tr>
							<td>
								<div class="input-group">
									<%= f.label 'Fecha de Compra' %>
									<%= f.date_field :purchase_date, class: "form-control", placeholder: "Fecha de Compra" %>
								</div>
							</td>
							<td>
								<div class="input-group">
									<%= f.label 'Precio de Compra' %>
									<%= f.text_field :purchase_price, class: "form-control", placeholder: "Precio de Compra" %>
								</div>
							</td>
						</tr>
						<tr>
							<td>
								<div class="input-group">
									<%= f.label 'Comisión de Compra' %>
									<%= f.text_field :purchase_commission, class: "form-control", placeholder: "Comisión de Compra" %>
								</div>
							</td>
							<td>
								<div class="input-group">
									<%= f.label 'IVA Comisión de Compra' %>
									<%= f.text_field :purchase_commission_iva, class: "form-control", placeholder: "IVA Comisión de Compra" %>
								</div>
							</td>
						</tr>
						<tr>
							<td>
								<div class="input-group">
									<%= f.label 'Dº Mercado de Compra' %>
									<%= f.text_field :purchase_market_right, class: "form-control", placeholder: "Dº Mercado de Compra" %>
								</div>
							</td>
							<td>
								<div class="input-group">
									<%= f.label 'IVA Dº Mercado de Compra' %>
									<%= f.text_field :purchase_market_right_iva, class: "form-control", placeholder: "IVA Dº Mercado de Compra" %>
								</div>
							</td>
						</tr>
						<tr>
							<td>
								<div class="input-group">
									<%= f.label 'Subtotal' %>
									<%= f.text_field :subtotal_purchase, class: "form-control", readonly: true %>
								</div>
							</td>
							<td>
								<div class="input-group">
									<%= f.label 'Impuestos' %>
									<%= f.text_field :tax_purchase, class: "form-control", readonly: true %>
								</div>
							</td>
						</tr>
						<tr>
							<td colspan="2" align="center">
								<div class="input-group">
									<%= f.label 'Total' %>
									<%= f.text_field :total_purchase, class: "form-control", readonly: true %>
								</div>
							</td>
						</tr>
					</table>
				</div>
				
				<%= render 'current_purchase_rate_chart' %>
			</div>
		</div>
	</div>
	
			
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Venta</h3>
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-lg-8">
					<table class="table">
						<tr>
							<td>
								<div class="input-group">
									<%= f.label 'Fecha de Venta' %>
									<%= f.date_field :sale_date, class: "form-control", placeholder: "Fecha de Venta" %>
								</div>
							</td>
							<td>
								<div class="input-group">
									<%= f.label 'Precio de Venta' %>
									<%= f.text_field :sale_price, class: "form-control", placeholder: "Precio de Venta" %>
								</div>
							</td>
						</tr>
						<tr>
							<td>
								<div class="input-group">
									<%= f.label 'Comisión de Venta' %>
									<%= f.text_field :sale_commission, class: "form-control", placeholder: "Comisión de Venta" %>
								</div>
							</td>
							<td>
								<div class="input-group">
									<%= f.label 'IVA Comisión de Venta' %>
									<%= f.text_field :sale_commission_iva, class: "form-control", placeholder: "IVA Comisión de Venta" %>
								</div>
							</td>
						</tr>
						<tr>
							<td>
								<div class="input-group">
									<%= f.label 'Dº Mercado de Venta' %>
									<%= f.text_field :sale_market_right, class: "form-control", placeholder: "Dº Mercado de Venta" %>
								</div>
							</td>
							<td>
								<div class="input-group">
									<%= f.label 'IVA Dº Mercado de Venta' %>
									<%= f.text_field :sale_market_right_iva, class: "form-control", placeholder: "IVA Dº Mercado de Venta" %>
								</div>
							</td>
						</tr>
						<tr>
							<td>
								<div class="input-group">
									<%= f.label 'Subtotal' %>
									<%= f.text_field :subtotal_sale, class: "form-control", readonly: true %>
								</div>
							</td>
							<td>
								<div class="input-group">
									<%= f.label 'Impuestos' %>
									<%= f.text_field :tax_sale, class: "form-control", readonly: true %>
								</div>
							</td>
						</tr>
						<tr>
							<td colspan="2" align="center">
								<div class="input-group">
									<%= f.label 'Total' %>
									<%= f.text_field :total_sale, class: "form-control", readonly: true %>
								</div>
							</td>
						</tr>
					</table>
				</div>
				<%= render 'current_sale_rate_chart' %>
			</div>
		</div>
	</div>
		
	<div class="actions">
		<%= f.submit 'Guardar', class: "btn btn-default"%>
	</div>
<% end %>

app/views/my_stocks/_index.html.erb
<div class="panel panel-dafault">
	<div class="panel-heading">Mis acciones y bonos</div>
	<div align="right"><td><%= link_to 'Nueva', new_my_stock_path, class: "btn btn-default" %></td></div>
	<table class="table">
		<thead>
			<th>Símbolo</th>
			<th>Cantidad</th>
			<th>Fecha Compra</th>
			<th>Precio Compra</th>
			<th>Total Compra</th>
			<th>Fecha Venta</th>
			<th>Precio Venta</th>
			<th>Total Venta</th>
			<th>Resultado</th>
			<th>Var. %</th>
			<th>Días</th>
			<th>Anual</th>
		</thead>
		<tbody>
			<% total_result = 0 %>
			<% total_current_result = 0 %>
			<% @my_stocks.each do |my_stock| %>
				<tr <%= my_stock.sale_date.nil? ? "" : "class=sold-stock" %> >
					<th><%= link_to my_stock.symbol, my_stock_path(my_stock) %></th>
					<td class="result-column"><%= my_stock.quantity %></td>
					<td><%= my_stock.purchase_date %></td>
					<td class="result-column"><%= number_to_currency(my_stock.purchase_price) %></td>
					<td class="result-column"><%= number_to_currency(my_stock.total_purchase) %></td>
					<td><%= my_stock.sale_date %></td>
					<td class="result-column"><%= number_to_currency(my_stock.showed_sale_price) %></td>
					<td class="result-column"><%= number_to_currency(my_stock.total_sale) %></td>
					<td class="result-column" style="color: <%= (my_stock.result >= 0)? "green" : "red" %>"><%= number_to_currency(my_stock.result) %></td>
					<td class="result-column" style="color: <%= (my_stock.result >= 0)? "green" : "red" %>"><%= my_stock.variation %></td>
					<td class="result-column"><%= my_stock.days %></td>
					<td class="result-column" style="color: <%= (my_stock.result >= 0)? "green" : "red" %>"><%= my_stock.variation_anual %></td>
					<td align="right"><%= link_to 'Editar', edit_my_stock_path(my_stock) %></td>
				</tr>
				<% total_result += my_stock.result %>
				<% total_current_result += (my_stock.sale_date.nil?) ?  my_stock.result : 0 %>
			<% end %>
		</tbody>
		<tfoot>
			<tr>
				<td colspan="6"></td>
				<th colspan="2" class="result-column">Activos actuales</th>
				<th class="result-column" style="color: <%= (total_current_result >= 0)? "green" : "red" %>"><%= number_to_currency(total_current_result) %></th>
				<td colspan="3"></td>
			</tr>
			<tr>
				<td colspan="6"></td>
				<th colspan="2" class="result-column">Total histórico</th>
				<th class="result-column" style="color: <%= (total_result >= 0)? "green" : "red" %>"><%= number_to_currency(total_result) %></th>
				<td colspan="3"></td>
			</tr>
		</tfoot>
	</table>
</div>
<div align="center">

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Gráfico de Tenencias
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="flot-chart">
                    <div class="flot-chart-content" id="flot-pie-chart"></div>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>
<!-- /.row -->
</div>
<%= javascript_include_tag "flot/jquery.js" %>
<%= javascript_include_tag "flot/excanvas.js" %>
<%= javascript_include_tag "flot/jquery.flot.js" %>
<%= javascript_include_tag "flot/jquery.flot.pie.js" %>
<%= javascript_include_tag "flot/jquery.flot.tooltip.js" %>
<%= javascript_include_tag "flot/flot-data.js" %>

app/views/my_stocks/edit.html.erb
<%= render 'form' %>

<%= link_to 'Volver', root_path %>

app/views/my_stocks/new.html.erb
<%= render 'form' %>

<%= link_to 'Volver', root_path %>

app/views/my_stocks/show.html.erb
<h3>Activo: <%= @stock.symbol %> </h3>

<p>No implementado aún </p>

<%= link_to 'Volver', root_path %>