config/routes.rb
Rails.application.routes.draw do

  get 'list_stock/index'

  get 'list_stock/new'

  get 'list_stock/create'

  get 'list_stock/edite'

  get 'list_stock/delete'

  resources :stocks

  root 'home#index'
  
  devise_for :users
  
  get 'home/index'

  resources :my_stocks
  resources :rate_charts

  get 'rate_charts_current' => 'rate_charts#current'

  get 'update_stock_list' => 'stocks#update_stock_list'

  get 'current_assets' => 'my_stocks#current_assets'

  resources :list_stocks
  

end

app/models/rate_chart.rb
# == Schema Information
#
# Table name: rate_charts
#
#  id               :integer          not null, primary key
#  since            :date
#  until            :date
#  commission       :decimal(12, 2)
#  commission_iva   :decimal(12, 2)
#  market_right     :decimal(12, 2)
#  market_right_iva :decimal(12, 2)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  user_id          :integer
#  type_stock       :integer
#  commission_min   :decimal(12, 2)
#

class RateChart < ActiveRecord::Base
  belongs_to :user
  
  def type_stock_description
    case type_stock
    when 1
      "Acciones"
    when 2
      "Bonos"
    else
      "Desconocido"
    end
  end

  def current (user = self.user, dateParam = DateTime.parse(params[:date]), type = params[:type].to_i, operation = params[:operation].to_s)
    @current_rate_chart = nil
    if dateParam == nil
      date = Date.today
    else
      date = dateParam
    end
    @operation = operation
    @rate_charts = user.rate_charts
    @current_rate_chart = @rate_charts.detect do |rc| 
      rc.since <= date && (rc.until != nil) ? date <= rc.until : false && rc.type_stock == type
    end
    if @current_rate_chart == nil
      @current_rate_chart = @rate_charts.detect{ |rc| rc.until == nil && rc.type_stock == type }
    end
    @current_rate_chart
  end
end

app/controllers/rate_charts_controller.rb
class RateChartsController < ApplicationController
  before_filter :get_rate_chart, only: [:edit, :destroy]
  before_filter :correct_user!, only: [:edit, :update, :destroy]
  before_action :get_rate_charts_user, only: [:index, :current]
  
  def index
    
  end

  def show
  end

  def edit
  end

  def update
    if @rate_chart.update(rate_chart_params)
      redirect_to rate_charts_path
    else
      flash[:error] = "Error al actualizar"
      render :edit
    end
  end

  def new
    @rate_chart = RateChart.new
  end

  def create
    @rate_chart = RateChart.new(rate_chart_params)
    @rate_chart.user = current_user
    
    if @rate_chart.save
      redirect_to rate_charts_path
    else
      flash[:error] = "Error al guardar"
      render :new
    end
  end

  def current
    @current_rate_chart = nil
    date = DateTime.parse(params[:date])
    type = params[:type].to_i
    @operation = params[:operation].to_s
    @current_rate_chart = @rate_charts.detect do |rc| 
      rc.since <= date && (rc.until != nil) ? date <= rc.until : false && rc.type_stock == type
    end
    if @current_rate_chart == nil
      @current_rate_chart = @rate_charts.detect{ |rc| rc.until == nil && rc.type_stock == type }
    end
    @current_rate_chart
  end

  protected
  
  def get_rate_chart
    @rate_chart = RateChart.find(params[:id])
  end
  
  def correct_user!
    @rate_chart = RateChart.find(params[:id])
    if @rate_chart.user != current_user
      flash[:error] = "No podes hacer eso!"
      redirect_to root_path
    end
  end
  
  def rate_chart_params
    params.require(:rate_chart).permit(:since, :until, :commission, :commission_iva, 
        :commission_min, :market_right, :market_right_iva, :user_id, :type_stock)
  end
  
  def get_rate_charts_user
    @rate_charts = current_user.rate_charts
  end
end

app/helpers/rate_charts_helper.rb
module RateChartsHelper
end

app/views/rate_charts/_form.html.erb
<%= form_for(@rate_chart) do |f| %>
	<% if @rate_chart.errors.any? %>
		<div id="error_explanation">
			<h4><%= pluralize(@rate_chart.errors.count, "error") %> prohibited this rate chart from being saved:</h4>
			
			<% @rate_chart.errors.full_messages.each do |message| %>
				<div class="alert alert-danger" role="alert">
					<p><%= message %></p>
				</div>
			<% end %>
		</div>
	<% end %>
		
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Cuadro Tarifario</h3>
		</div>
		<div class="panel-body">
			<table class="table">
				<tr>
					<td>
						<div class="input-group">
							<%= f.label 'Tipo' %>
							<%= f.select(:type_stock, options_for_select([["Acción", 1],["Bono", 2]], @rate_chart.type_stock), {}, {class: "form-control"}) %>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<div class="input-group">
							<%= f.label 'Desde' %>
							<%= f.date_field :since, class: "form-control", placeholder: "Desde" %>
						</div>
					</td>
					<td>
						<div class="input-group">
							<%= f.label 'Hasta' %>
							<%= f.date_field :until, class: "form-control", placeholder: "Hasta" %>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<div class="input-group">
							<%= f.label 'Comisión' %>
							<%= f.text_field :commission, class: "form-control", placeholder: "Comisión" %>
						</div>
					</td>
					<td>
						<div class="input-group">
							<%= f.label 'Comisión mínima' %>
							<%= f.text_field :commission_min, class: "form-control", placeholder: "Comisión mínima" %>
						</div>
					</td>
					<td>
						<div class="input-group">
							<%= f.label 'IVA Comisión' %>
							<%= f.text_field :commission_iva, class: "form-control", placeholder: "IVA Comisión" %>
						</div>
					</td>
				</tr>
				<tr>
					<td colspan="2">
						<div class="input-group">
							<%= f.label 'Dº Mercado' %>
							<%= f.text_field :market_right, class: "form-control", placeholder: "Dº Mercado" %>
						</div>
					</td>
					<td>
						<div class="input-group">
							<%= f.label 'IVA Dº Mercado' %>
							<%= f.text_field :market_right_iva, class: "form-control", placeholder: "IVA Dº Mercado" %>
						</div>
					</td>
				</tr>
			</table>
		</div>
	</div>
		
	<div class="actions">
		<%= f.submit 'Guardar', class: "btn btn-default"%>
	</div>
<% end %>

app/views/rate_charts/create.html.erb
<h1>RateCharts#create</h1>
<p>Find me in app/views/rate_charts/create.html.erb</p>

app/views/rate_charts/current.js.erb
<% if @current_rate_chart %>
	<% commission 			= @current_rate_chart.commission %>
	<% commission_min 		= @current_rate_chart.commission_min %>
	<% commission_iva 		= @current_rate_chart.commission_iva %>
	<% market_right 		= @current_rate_chart.market_right %>
	<% market_right_iva 	= @current_rate_chart.market_right_iva %>
<% else %>
	<% commission 			= 0 %>
	<% commission_min 		= 0 %>
	<% commission_iva 		= 0 %>
	<% market_right 		= 0 %>
	<% market_right_iva 	= 0 %>
<% end %>
<% if @operation == "purchase" %> 
	<%= puts @operation %>
	$("#purchase_current_rate_chart_commission").text("<%= commission %>");
	$("#purchase_current_rate_chart_commission_min").text("<%= commission_min %>");
	$("#purchase_current_rate_chart_commission_iva").text("<%= commission_iva %>");
	$("#purchase_current_rate_chart_market_right").text("<%= market_right %>");
	$("#purchase_current_rate_chart_market_right_iva").text("<%= market_right_iva %>");
<% else %>
	<%= puts @operation %>
	$("#sale_current_rate_chart_commission").text("<%= commission %>");
	$("#sale_current_rate_chart_commission_min").text("<%= commission_min %>");
	$("#sale_current_rate_chart_commission_iva").text("<%= commission_iva %>");
	$("#sale_current_rate_chart_market_right").text("<%= market_right %>");
	$("#sale_current_rate_chart_market_right_iva").text("<%= market_right_iva %>");
<% end %>

app/views/rate_charts/edit.html.erb
<%= render 'form' %>

<%= link_to 'Volver', :back %>

app/views/rate_charts/index.html.erb
<div class="panel panel-dafault">
	<div class="panel-heading">Mis acciones y bonos</div>
	<div align="right"><td><%= link_to 'Nuevo Cuadro', new_rate_chart_path, class: "btn btn-default" %></td></div>
	<table class="table">
		<thead>
			<th>Tipo</th>
			<th>Desde</th>
			<th>Hasta</th>
			<th>Comisión (%)</th>
			<th>Com. Mín.</th>
			<th>IVA Com. (%)</th>
			<th>Dº Mercado (%)</th>
			<th>IVA Dº Merc. (%)</th>
		</thead>
		<tbody>
			<% @rate_charts.each do |rate_chart| %>
				<tr>
					<th><%= rate_chart.type_stock_description %></th>
					<td><%= rate_chart.since %></td>
					<td><%= rate_chart.until %></td>
					<td><%= rate_chart.commission %></td>
					<td><%= number_to_currency(rate_chart.commission_min) %></td>
					<td><%= rate_chart.commission_iva %></td>
					<td><%= rate_chart.market_right %></td>
					<td><%= rate_chart.market_right_iva %></td>
					<td><%= link_to 'Editar', edit_rate_chart_path(rate_chart) %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/rate_charts/new.html.erb
<%= render 'form' %>

<%= link_to 'Volver', :back %>

app/views/rate_charts/show.html.erb
<h1>RateCharts#show</h1>
<p>Find me in app/views/rate_charts/show.html.erb</p>

app/views/rate_charts/update.html.erb
<h1>RateCharts#update</h1>
<p>Find me in app/views/rate_charts/update.html.erb</p>