config/routes.rb
Rails.application.routes.draw do

  get 'list_stock/index'

  get 'list_stock/new'

  get 'list_stock/create'

  get 'list_stock/edite'

  get 'list_stock/delete'

  resources :stocks

  root 'home#index'
  
  devise_for :users
  
  get 'home/index'

  resources :my_stocks
  resources :rate_charts

  get 'rate_charts_current' => 'rate_charts#current'

  get 'update_stock_list' => 'stocks#update_stock_list'

  get 'current_assets' => 'my_stocks#current_assets'

  resources :list_stocks
  

end

app/models/list_stock.rb
# == Schema Information
#
# Table name: list_stocks
#
#  id         :integer          not null, primary key
#  name       :string
#  market     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ListStock < ActiveRecord::Base
	validates :name, presence: true
	validates :market, presence: true
	validates :name, uniqueness: { scope: :market }

	def complete_name
		self.name.upcase + "." + self.market.upcase
	end
end

app/controllers/list_stocks_controller.rb
class ListStocksController < ApplicationController
  before_action :set_stock, only: [:edit, :update, :show, :destroy]
  def index
    @saved_stocks = ListStock.all
  end

  def show
  end

  def new
    @stock = ListStock.new
  end

  def create
    @stock = ListStock.new(list_stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to list_stocks_path, notice: 'Activo agregado correctamente.' }
        format.json { render :index, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @stock.update(list_stock_params)
        format.html { redirect_to list_stocks_path, notice: 'Activo actualizado correctamente.' }
        format.json { render :index, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to list_stocks_path, notice: 'Activo eliminado correctamente.' }
      format.json { head :no_content }
    end
  end

  private

    def set_stock
      @stock = ListStock.find(params[:id])
    end

    def list_stock_params
      params.require(:list_stock).permit(:name, :market)
    end
end

app/helpers/list_stock_helper.rb
module ListStockHelper
end

app/views/list_stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
	<% if @stock.errors.any? %>
		<div id="error_explanation">
			<h4><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h4>
			
			<% @stock.errors.full_messages.each do |message| %>
				<div class="alert alert-danger" role="alert">
					<p><%= message %></p>
				</div>
			<% end %>
		</div>
	<% end %>
		
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Activo</h3>
		</div>
		<div class="panel-body">
			<table class="table">
				<tr>
					<td>
						<div class="input-group">
							<%= f.label 'Símbolo' %>
							<%= f.text_field :name, class: "form-control", placeholder: "Símbolo" %>
						</div>
					</td>
					<td>
						<div class="input-group">
							<%= f.label 'Mercado' %>
							<%= f.text_field :market, class: "form-control", placeholder: "Mercado" %>
						</div>
					</td>
				</tr>
			</table>
		</div>
	</div>
		
	<div class="actions">
		<%= f.submit 'Guardar', class: "btn btn-default"%>
	</div>
<% end %>

app/views/list_stocks/create.html.erb
<h1>ListStock#create</h1>
<p>Find me in app/views/list_stock/create.html.erb</p>

app/views/list_stocks/delete.html.erb
<h1>ListStock#delete</h1>
<p>Find me in app/views/list_stock/delete.html.erb</p>

app/views/list_stocks/edit.html.erb
<%= render 'form' %>

<%= link_to 'Volver', list_stocks_path %>

app/views/list_stocks/index.html.erb
<div class="panel panel-dafault">
	<div class="panel-heading">Activos del Sistema</div>
	<div align="right"><td><%= link_to 'Nueva', new_list_stock_path, class: "btn btn-default" %></td></div>
	<table class="table">
	    <thead>
	      <tr>
	        <th>Nombre</th>
	        <th>Símbolo</th>
	        <th>Mercado</th>
	        <th></th>
	        <th></th>
	      </tr>
	    </thead>

	    <tbody>
	      <% @saved_stocks.each do |ss| %>
	        <tr>
	          <td><%= ss.complete_name %></td>
	          <td><%= ss.name %></td>
	          <td><%= ss.market %></td>
	          <td><%= link_to "Editar", edit_list_stock_path(ss.id) %></td>
	          <td><%= link_to "Eliminar", list_stock_path(ss), method: :delete, data: { confirm: "Estás seguro?" } %></td>
	        </tr>
	      <% end %>
	    </tbody>
	</table>
</div>

app/views/list_stocks/new.html.erb
<%= render 'form' %>

<%= link_to 'Volver', list_stocks_path %>