config/routes.rb
Rails.application.routes.draw do

  get 'list_stock/index'

  get 'list_stock/new'

  get 'list_stock/create'

  get 'list_stock/edite'

  get 'list_stock/delete'

  resources :stocks

  root 'home#index'
  
  devise_for :users
  
  get 'home/index'

  resources :my_stocks
  resources :rate_charts

  get 'rate_charts_current' => 'rate_charts#current'

  get 'update_stock_list' => 'stocks#update_stock_list'

  get 'current_assets' => 'my_stocks#current_assets'

  resources :list_stocks
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Trading" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application", "#{controller_name}" %>


    <!-- Custom Fonts -->
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">


    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body class="<%= controller_name %> <%= action_name %>">

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "GerTrading", root_path, class: "navbar-brand"  %>
            </div>
            <!-- /.navbar-header -->
            <% if user_signed_in? %>
              <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-line-chart fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <a href="<%= root_path %>">
                                <div>
                                    <strong>Mis Activos</strong>
                                    <span class="pull-right text-muted">
                                        <em>Resultados</em>
                                    </span>
                                </div>
                                <div>Ver el resultado de sus activos</div>
                            </a>
                        </li>
                        <li>
                            <a href="<%= stocks_path %>">
                                <div>
                                    <strong>Cotizaciones</strong>
                                    <span class="pull-right text-muted">
                                        <em>Al cierre anterior</em>
                                    </span>
                                </div>
                                <div>Ver últimas cotizaciones de acciones y bonos</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="<%= rate_charts_path %>">
                                <div>
                                    <strong>Cuadros Tarifarios</strong>
                                    <span class="pull-right text-muted">
                                        <em>Propios</em>
                                    </span>
                                </div>
                                <div>Configure los cuadros tarifarios según su operador de bolsa</div>
                            </a>
                        </li>
                    </ul>
                </li>
                <!-- /.dropdown-acciones -->

                <% if current_user.email == "ger@man.com" %>
                  <!-- /.dropdown -->
                  <li class="dropdown">
                      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                          <i class="fa fa-tasks fa-fw"></i>  <i class="fa fa-caret-down"></i>
                      </a>
                      <ul class="dropdown-menu dropdown-user">
                          <!-- <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a></li> -->
                          <li><a href="<%= update_stock_list_path %>"><i class="fa fa-gear fa-fw"></i> Actualizar BD</a></li>
                          <li><a href="<%= list_stocks_path %>"><i class="fa fa-gear fa-fw"></i> Administrar Activos</a></li>
                      </ul>
                  </li>
                  <!-- /.dropdown-tasks -->
                <% end %>

                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <!-- <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a></li> -->
                        <li><a href="<%= edit_user_registration_path %>"><i class="fa fa-gear fa-fw"></i> Cuenta</a></li>
                        <li class="divider"></li>
                        <li><a href="<%= destroy_user_session_path %>" data-method="delete"><i class="fa fa-sign-out fa-fw""></i> Cerrar sesión</a></li>
                    </ul>
                </li>
                <!-- /.dropdown-user -->
              </ul>
              <!-- /.navbar-header -->
            <% end %>
        </nav>
    </div>
<!--
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">Trading</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
          </ul>
        </div>
      </div>
    </div>
-->
    <div class="container">
    <% if user_signed_in? %>
      <div class="row">
        <div class="col-lg-12">
    			<%= bootstrap_flash %>
    			
    			<h1> Bienvenido a GerTrading, <%= current_user.email %></h1>
    			
    			<%= yield %>
        </div>
        <!--
        <div class="col-lg-2">
          <div class="well sidebar-nav">
            <h3>Opciones</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Cuenta</li>
              <li><%= link_to "Editar", edit_user_registration_path  %></li>
              <li><%= link_to "Salir", destroy_user_session_path, method: :delete  %></li>
            </ul>
          </div><!--/.well ->
        </div><!---/span->
        -->
      </div><!--/row-->
  	<% else %>
      <h1> Bienvenido a GerTrading.</h1>
      <p>Sistema de monitoreo de Acciones y Bonos. Antes de continuar, debe registrarse.</p>
      <!--<%= bootstrap_flash %> -->
      <%= yield %>
  	<% end %>
        <footer>
          <p>&copy; Germán Martínez 2016</p>
        </footer>
    </div> <!-- /container -->
  </body>
</html>